/// Flutter icons FacebookIcon
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FacebookIcon
///      fonts:
///       - asset: fonts/FacebookIcon.ttf
///
/// 
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class FacebookIcon {
  FacebookIcon._();

  static const _kFontFam = 'FacebookIcon';

  static const IconData facebook_circled = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData account_balance_wallet = const IconData(0xf008, fontFamily: _kFontFam);
}
